RISC-KC/basic_rv32s

RV32I/modules/Trap_Controller.v

Corrected the existing `rst` signal to `reset` for consistency across module designs.

[Feat] Correct rst signal to reset signal

---

RV32I/modules/RV32I46F.v
RV32I/testbenches/RV32I46F_tb.v

Still need some debugging and test scenario designing. 
But the draft of the RV32I46Fs' top module design and its testbench file is probably done. 
Now we have to get the changes from Trap_Controller's `rst` to `reset` signal. 
And checkout to Instruction Memory branch to write the RV32I46F's testbench scenario.

Draft implementation of RV32I46F.v and its testbench

---

RV32I/modules/Instruction_Decoder.v
RV32I/testbenches/Instruction_Decoder_tb.v
RV32I/testbenches/results/Instruction_Decoder_result.vvp
RV32I/testbenches/results/waveforms/Instruction_Decoder_tb_result.vcd

While modifying the **Instruction Decoder** to resolve the instruction selection issue between `dbg_instruction` (debug instruction) and `im_instruction` (instruction memory instruction), the **Instruction Decoder** previously included both `dbg_instruction` and `im_instruction` internally for selecting the instruction to decode.
Eventually, this selection functionality was initially addressed internally but was later moved to the top-level module **RV32I46F.R5**, aligning with the original processor design that placed the **MUX** externally, similar to other **MUX** configurations.
At that stage, the selected instruction, determined by the `debug_mode` control signal, was needed. Consequently, it was decided to rename the existing signal instr to the more explicit name instruction. 
This …

[Feat] Modified signal name by revising instr signal to instruction signal

---

RV32I/modules/EX_MEM_Register.v
RV32I/modules/ID_EX_Register.v
RV32I/modules/MEM_WB_Register.v
RV32I/testbenches/EX_MEM_Register_tb.v
RV32I/testbenches/ID_EX_Register_tb.v
RV32I/testbenches/MEM_WB_Register_tb.v
RV32I/testbenches/results/EX_MEM_Register_result.vvp
RV32I/testbenches/results/ID_EX_Register_result.vvp
RV32I/testbenches/results/MEM_WB_Register_result.vvp
RV32I/testbenches/results/waveforms/EX_MEM_Register_tb_result.vcd
RV32I/testbenches/results/waveforms/ID_EX_Register_tb_result.vcd
RV32I/testbenches/results/waveforms/MEM_WB_Register_tb_result.vcd

Added the missing `rd` signal required for the **Register File**'s write operation in the WriteBack pipeline stage.
Previously, this signal had not been pipelined. 
Now, the following pipeline registers include the `rd` (register destination) signal.
- ID_EX_Register
- EX_MEM_Register
- MEM_WB_Register

[Feat] Add rd signal from to each pipeline registers

---

RV32I/modules/MEM_WB_Register.v
RV32I/testbenches/MEM_WB_Register_tb.v
RV32I/testbenches/results/MEM_WB_Register_result.vvp
RV32I/testbenches/results/waveforms/MEM_WB_Register_tb_result.vcd

Revised existing `MEM_register_file_write_data`, `WB_register_file_write_data` to 
`MEM_byte_enable_logic_register_file_write_data`, `WB_byte_enable_logic_register_file_write_data` for **RV32I46F_5SP** top-module implementation.

[Feat] Revise MEM_WB_Register read_data signal name to BERF_WD and its testbench

---

RV32I/modules/Forward_Unit.v
RV32I/testbenches/Forward_Unit_tb.v
RV32I/testbenches/results/Forward_Unit_result.vvp
RV32I/testbenches/results/waveforms/ForwardUnit_tb.vcd

Revised existing `MEM_read_data`, to `MEM_byte_enable_logic_register_file_write_data` for **RV32I46F_5SP** top-module implementation.

[Feat] Revise Forward_Unit read_data signal name to BERF_WD and its testbench

---

RV32I/modules/Hazard_Unit.v

Removed the existing `EX_register_write_enable` signal from the **Hazard Unit**, as it was unused in the logic.

[Feat] Revise Hazard Unit by removing unused signal EX_register_write_enable

---

RV32I/modules/Byte_Enable_Logic.v

Existing `address` was 32-bit width, but since it only needs 2-bit of LSBs so it's reduced to 2-bit. 
This is for internal _misaligned memory address access exception_ detection logic.

[Feat] Revise BE_Logic by properly allocating bit width for misalignment detection address signal

---

RV32I/modules/Byte_Enable_Logic.v

Since the ***LOAD*** and ***STORE MISALIGNMENT*** detection is handled in **Exception Detector**,
the unused `misaligned` output signal has been removed.

[Feat] Revise Byte Enable Logic by removing address misalignment detection logic

---

RV32I/modules/Exception_Detector.v

- Exceptions are now detected independently in both the _ID_ and _EX pipeline stages_.
- The previous integrated ***MISALIGNED MEMORY*** exception has been separated into ***MISALIGNED STORE*** and ***MISALIGNED LOAD*** exceptions. 
This aligns with the **RISC-V ISA Manual**, which specifies distinct exception codes for each type within the `CSR; mcause`.
Logic's test has been verified without its individual testbench by testing it in top module in Vivado and iverilog.
**Note**: Initially, an ***ILLEGAL INSTRUCTION*** exception was intended to handle write accesses to undefined `CSR`s. 
However, due to significant increases in design complexity and verification effort, this implementation has been temporarily suspended. The related code sections have been commented out to facilitate …

[Feat] Revise Exception Detector to separately handle MISALIGNED STORE and LOAD exceptions

---

RV32I/modules/Trap_Controller.v

Since **Exception Detector** module has been revised to Synchronous, **Trap Controller**'s internal Trap Handling routine(PTH) execution has to be targeted 1 Clock Cycle delayed time. 
This revision applies the delay from revised **Synchronous Exception Detector**.
Logic's test has been verified without its individual testbench by testing it in top module in Vivado and iverilog.

[Feat] Revise Trap Controller PTH for Synchronous Exception Detector

---

RV32I/modules/Exception_Detector.v

**RV32I46F_5SP**를 FPGA에 구현하기 위해서 Vivado를 통해 시뮬레이션을 돌려봤습니다.
그 중 Post Synthesis Timing Simulation(PSTS)에서 exception 발생 이후 trap_handling(PTH 포함)로 넘어가는데에서 파형이 UNKNOWN으로 바뀌는 것을 확인했고, 이를 해결하기 위해 **Exception Detector** 모듈의 출력 신호를 동기식으로 수정하기로 했습니다.
파형을 자세히 보면, 0x0000_1000 Trap Handler 주소로 분기하기 이전에 `trap_status` 신호가 본래 한가지로 특정되어 진행되어야하는 로직에서 한 클럭 사이클 이내에 여러가지 코드로 변화하는 것을 확인하였고, 이와 같은 불안정성이 직접적인 원인이 될 수 있다고 판단해 clk의 rising edge에서만 값을 출력해 이후 다음 클럭 사이클까지 값의 변화가 최대한 없도록 보장하여 불안정성을 없애고자 하였습니다.
수정된 로직은 개별 테스트벤치 없이 Vivado와 iverilog에서 탑 모듈 시뮬레이션을 통해 검증되었습니다.
To implement the **RV32I46F_5SP** architecture on FPGA, a simulation was conducted using Vivado. 
During the _Post Synthesis Timing Simulation_ (PSTS), an issue was identified where signals transitioned to an UNKNOWN state during the transition from …

[Feat] Revise Exception Detector output to Synchronous for FPGA Implementation

---

RV32I/modules/Hazard_Unit.v

- Now `pth_done_flush` logic includes **MEM_WB_Register** flush
(since **Exception Detector** module has been revised to ***Synchronous***, `pth_done_flush` execution also has to be targeted 1 Clock Cycle delayed time.)
Logic's test has been verified without its individual testbench by testing it in top module in Vivado and iverilog.

[Feat] Revise Hazard Unit for Synchronous Exception Detector

---

RV32I/modules/Register_File_Debug.v

**46F5SP_SoC_TOP** 모듈의 FPGA 구현과 실시간 검증, 디버깅을 위해서 **Register File Debug** 모듈이 추가되었습니다.
이 디버그 모듈은 기존 **Register File** 모듈에서 디버그용 출력 신호 2개와 그 로직을 추가한 것입니다.
- `write_reg` (목적지 레지스터 주소; rd)
- `write_data` (해당 레지스터에 쓰여질 데이터 값)
이를 통해 ***RV32I46F_5SP*** 프로세서의 WriteBack 파이프라인 단계를 FPGA 검증 과정에서 확인할 수 있습니다. 
**Register File Debug** module has been added for the **46F5SP_SoC_TOP** FPGA implementation to support runtime verification and debugging. 
This standalone debug module extends the original **Register File** by exposing two additional outputs
- `write_reg` (the destination register address)
- `write_data` (the data value written)
which reflect the WriteBack stage of the …

[Feat] Implement Register File Debug module for 46F5SP_SoC_TOP FPGA verification and debugging

---

RV32I/modules/Program_Counter.v

이를 위해 각종 모듈에 클럭 활성화 신호 `clk_enable`를 input 으로 추가하였고, 해당 신호의 통제에 따라 로직을 작동할 수 있도록 변경사항을 적용했습니다.
The **46F5SP_SoC_TOP** module supports a sequential execution mode, enabling step-by-step clock operation triggered by external button inputs to observe signal values at specific clock cycles.
To implement this functionality, a clock enable signal (`clk_enable`) has been introduced as an input to various modules. 
Logic within these modules has been modified to operate conditionally based on the state of this control signal.
Logic's test has been verified without its individual …

[Feat] Revise Program Counter by adding clock enable signal for 46F5SP_SoC_TOP FPGA verification and debugging

---

RV32I/modules/Exception_Detector.v

이를 위해 각종 모듈에 클럭 활성화 신호 `clk_enable`를 input 으로 추가하였고, 해당 신호의 통제에 따라 로직을 작동할 수 있도록 변경사항을 적용했습니다.
The **46F5SP_SoC_TOP** module supports a sequential execution mode, enabling step-by-step clock operation triggered by external button inputs to observe signal values at specific clock cycles.
To implement this functionality, a clock enable signal (`clk_enable`) has been introduced as an input to various modules. 
Logic within these modules has been modified to operate conditionally based on the state of this control signal.
Logic's test has been verified without its individual …

[Feat] Revise Exception Detector by adding clock enable signal for 46F5SP_SoC_TOP FPGA verification and debugging

---

RV32I/modules/EX_MEM_Register.v
RV32I/modules/ID_EX_Register.v
RV32I/modules/IF_ID_Register.v
RV32I/modules/MEM_WB_Register.v

이를 위해 각종 모듈에 클럭 활성화 신호 `clk_enable`를 input 으로 추가하였고, 
해당 신호의 통제에 따라 로직을 작동할 수 있도록 변경사항을 적용했습니다.
기존 파이프라인 레지스터에서는 `flush`와 `reset`을 OR 처리하여 수행하였습니다. 예) *(if reset || flush)*
하지만 클럭 활성화 신호 `clk_enable` 이 추가되며 flush 자체는 시스템 구동 중에만 처리 가능해야 하기에, 
`reset`은 `clk_enable`의 값과 무관하게 로직을 처리하도록 하였고, `flush`는 `clk_enable`일 때만 처리할 수 있도록 이원화 하였습니다.
The **46F5SP_SoC_TOP** module supports a sequential execution mode, enabling step-by-step clock operation triggered by external button inputs to observe signal values at specific clock cycles.
To implement this functionality, a clock enable …

[Feat] Revise Pipeline Registers separating reset flush logic and adding clock enable signal

---

RV32I/modules/Data_Memory.v

이를 위해 각종 모듈에 클럭 활성화 신호 `clk_enable`를 input 으로 추가하였고, 해당 신호의 통제에 따라 로직을 작동할 수 있도록 변경사항을 적용했습니다.
- 이제 `clk_enable` 일 때만 쓰기가 수행됩니다.
The **46F5SP_SoC_TOP** module supports a sequential execution mode, enabling step-by-step clock operation triggered by external button inputs to observe signal values at specific clock cycles.
To implement this functionality, a clock enable signal (`clk_enable`) has been introduced as an input to various modules. 
Logic within these modules has been modified to operate conditionally based on the state of this control signal.
- Write is now …

[Feat] Revise Data Memory adding clock enable signal for 46F5SP_SoC_TOP FPGA verification and debugging

---

RV32I/modules/RV32I46F_5SP_Debug.v

**46F5SP_SoC_TOP** 모듈의 FPGA 구현과 실시간 검증, 디버깅을 위해서 별도의 Debug 신호와 출력 로직이 추가된 
***RV32I46F_5SP_Debug*** 코어가 구현되었습니다. 
이를 위해 각종 모듈에 클럭 활성화 신호 `clk_enable`를 input 으로 추가하였고, 
해당 신호의 통제에 따라 로직을 작동할 수 있도록 변경사항을 적용했습니다.
이를 통해 ***RV32I46F_5SP*** 프로세서의 WriteBack 파이프라인 단계를 FPGA 검증 과정에서 확인할 수 있습니다. 
기존 ***RV32I46F_5SP*** 프로세서가 FPGA 내에서 어떻게 동작하는지 확인하기 위하여, 
내부 값들을 출력하는 디버깅용 output 출력 신호들을 추가했습니다. 
현재는 **46F5SP_SoC_TOP** 모듈의 디버그 인터페이스에 맞게 다음과 같은 디버그 신호들을 출력합니다.
- **IF 단계** 프로그램 카운터 값
- **IF 단계** 명령어 값
- **EX 단계** ALU 결과 값
- **WB 단계** 쓰여질 레지스터 주솟값
- **WB 단계** 레지스터에 쓰여질 데이터값
본 `feat/rv32i46f_5sp_debug` 브랜치의 최초 commit; `41242d4` 에 보존되어있는 기타 debug 신호들을 output해서 더 많은 신호들의 값들을 모니터링, 디버깅할 수 있습니다. 
Vivado에서 …

[Feat] Implement RV32I46F_5SP_Debug core design by adding output signals for debugging

---

RV32I/modules/UART_TX.v

**46F5SP_SoC_TOP** 모듈의 FPGA 구현과 실시간 검증, 디버깅을 위해서 **UART TX** 모듈이 추가되었습니다.
이 모듈은 46F5SP_SoC_TOP 모듈이 FPGA에 다운로드 된 후, FPGA 보드의 데이터를 UART 통신으로 출력하기 위한 모듈입니다.
Digilent 社의 Nexys Video FPGA 보드에 탑재된 UART Bridge (FTDI FT232R USB-UART bridge)를 사용합니다. 
50MHz 동작 클럭에 맞춰 115200 baud로 설정했습니다. 
PC로 출력될 `tx_data`는 **UART Debug Controller**에게서 입력받아 처리됩니다.
이를 통해 ***RV32I46F_5SP*** 프로세서의 동작을 UART 통신 인터페이스를 통해 FPGA 검증 과정에서 확인할 수 있습니다. 
**UART TX** module has been added to the **46F5SP_SoC_TOP** for FPGA implementation, runtime verification, and debugging. This module facilitates UART communication to output data from the FPGA after the 46F5SP_SoC_TOP module is downloaded onto the board.
The …

[Feat] Implement UART TX for 46F5SP_SoC_TOP FPGA verification and debugging

---

RV32I/modules/RV32I46F_5SP_Debug.v

In line 508, the **ID EX Register** Pipeline Register's signal instance source has been connected wrong. 
This commit fixes this error.
`.ID_csr_read_data(csr_read_data),` to `.ID_csr_read_data(csr_read_out),`
- This change is from ***Synchronous CSR File implementation*** 
#154

[Feat] Revise RV32I46F 5SP Debug ID EX Register instance misconnected signal csr_read_data to csr_read_out

---

RV32I/modules/PC_Controller.v

While implementing 46F5SP's Dhrystone benchmark, we found a loop going in the middle of Dhrystone benchmark.
Debug log can be found at `#[2025.06.22.]` 
Unfortunately, the capture of the simulation waveform is missing. but this occurred because of 
**PC Controller**'s `next_pc` selection logic's decision source's priority issue.
This commit solves this issue.
---
The loop:
- PC 380: addi a0, sp, 64
a0 = 1000_7fa0
s3 = 0000_0000
- PC 384: jal ra, 2232
- PC = c3c
... Program running. a0, s3 no changes.
a0 = 1000_7fa0
s3 = 0000_0000
- PC c54: jalr zero, 0(ra)
PC = 388
...
- PC 38c: addi a0, sp, 32
a0 = 1000_7f80
s3 = 0000_0000
- PC 394: jal ra, 1460
PC = 948
...
- PC 968: addi s3, zero, 1
a0 = 1000_7f80
s1 = 0000_0001
...
- PC 970: lbu a0, 2(s1)
a0 = 0000_0000
s1 = 0000_0001
...
-PC 974: jal …

[Feat] Revise PC Controller next pc logic source priorities
